### PR TITLE
Improved Cast Support

### PR DESCRIPTION
**Pull request by n8detar**
Improved implementation of cast integration. Added proper cast button with basic theming and redid and simplified some of the backend JS. The title of the video is also sent to the cast device.

Full
Cast Button OFF/ON
Cast Button offCast Button ON

### CODE REVIEW

**Comment by bbilly1** [comment]
Oh nice, that looks good. I'll double check things a bit later. As far as I can see that will replace PR #141, right?

**Comment by n8detar** [comment]
I don't think the `cast` integration variable is being set on the home page. I tested without the setting condition and everything is working on both the videos page and the home page. So once the variable issue is cleared up this should be good to go.

**Comment by n8detar** [comment]
The latest commit makes it so the casted video starts at the same time position as it was in the browser. So if you start playing the video in the browser but then decide to cast it you don't need to skip to get back to the position you were at. With that added and the checks passing I think the integration is at a good place. I've done a lot of testing so I don't think there are any bugs left but other people should test it out in case I've missed something, so I won't add any more commits so that this can maybe finally be merged lol.

**Comment by bbilly1** [comment]
I've made a new unstable build. As far as I can tell, the cast variable should now be available throughout the views containing videos so the JS library will load if needed.

**Pull request merged**
