### PR TITLE
Fix: #210 - Download UI Box being removed when file is still processing

### PR DESCRIPTION
**Pull request by ainsey11**
The UI element is removed when the file has finished downloading, but is still being moved on disk to the storage destination. This means the user is presented with nothing in the UI yet the file is still being processed.

This PR is to add in a message just before the move_to_archive() function is called, with no expiry, so the webUI updates with a "Moving file" UI element so the user can see that the file is still in flight.

image

Eventually I would like to display the video name of the file being moved, but keeping large changes to a minimum whislt I still find my feet in the project

### CODE REVIEW

**Comment by ainsey11** [comment]
PR to resolve https://github.com/bbilly1/tubearchivist/issues/210

**Comment by bbilly1** [comment]
Nice, I think thats the right approach. 

So for "historical" reason, the set_message expires by default, so you can either pass a number as seconds, or False to make it permanent. I kjow, I know... J need to start write some doc strings on these classes...

So I was thinking, how about at the beginning of the move task, set a message that doesnt expire, and at the end send a message that maybe expires in 5secs or so? Then when the task completes, the message box doesnt linger too long?

**Comment by ainsey11** [comment]
Thanks @bbilly1 

I'll tweak and append a new commit in later today

Cheers
Rob

**Comment by ainsey11** [comment]
Updated to set a message on the move that never expires, followed by a message after the move with a 4 second expiry that states "completed"

Looks like this:
image

updated PR incoming

**Pull request merged**
